export const PricingData = [
    [
        {title: 'Basic' ,
        name: 'Web Design', 
        price: 1000, 
        para: 'Demand for technology is increasing heavily, so what are you waiting for?', 
        first:'UI Design',
        second:'UX Design',
        third:'Contacts'},
        {title: 'Standard' ,
        name: 'Web Design',
         price: 2000,
          para: 'Demand for technology is increasing heavily, so what are you waiting for?',
         first:'UI + UX + contacts',
        second:'Backend',
        third:'Responsive'},
        {title: 'Premium' ,
        name: 'Web Design',
         price: 3000,
          para: 'Demand for technology is increasing heavily, so what are you waiting for?',
         first:'UI + UX + contacts',
        second:'Backend',
        third:'Payment System'},
    ],
    [
        {title: 'Basic' ,
        name: 'Email Marketing',
         price: 1000,
          para: 'Learn how to build an email marketing strategy that is human and helpful and builds trust with your contacts.',
         first:'Master the fundamentals of email marketing.',},
        {title: 'Standard' ,
        name: 'Email Marketing',
         price: 2000,
          para: 'Learn how to build an email marketing strategy that is human and helpful and builds trust with your contacts.',
         first:'Your account will be full of personalized training recommendations tailored to you.',},
        {title: 'Premium' ,
        name: 'Email Marketing',
         price: 3000,
          para: 'Learn how to build an email marketing strategy that is human and helpful and builds trust with your contacts.',
         first:'With our certifications across 5 languages, you can enhance skills and stand out.',},
    ],
    [
        {title: 'Basic' ,
        name: 'Graphic Design',
         price: 1000,
          para: 'Graphic design for beginners including Graphic Design Theories, Photoshop, Illustrator, Indesign, CC & Creative Thinking',
         first:'Graphic design Theories',
        second:'Composition & layout rules',
        third:'creative thinking'},
        {title: 'Standard' ,
        name: 'Graphic Design',
         price: 2000,
          para: 'Graphic design for beginners including Graphic Design Theories, Photoshop, Illustrator, Indesign, CC & Creative Thinking',
         first:'color theory',
        second:'Grid systems',
        third:'How to use Photoshop in a creative way to create stunning Ads'},
        {title: 'Premium' ,
        name: 'Graphic Design',
         price: 3000,
          para: 'Graphic design for beginners including Graphic Design Theories, Photoshop, Illustrator, Indesign, CC & Creative Thinking',
         first:'how to create brochures, catalogs & flyers',
        second:'how to export your designs in different formats',
        third:'to speed up your workflow & speed up Illustrator performance as well'},
    ],
    [
        {title: 'Basic' ,
        name: 'Web Development',
         price: 1000,
          para: 'Our expert in-house team uses cutting edge technologies to build softwares and custom web applications that are stunning, robust and scalable.',
         first:'Web Application Development',
        second:'MEAN/MERN Stack Development',
        third:'Big Data Services'},
        {title: 'Standard' ,
        name: 'Web Development',
         price: 2000,
          para: 'Our expert in-house team uses cutting edge technologies to build softwares and custom web applications that are stunning, robust and scalable.',
         first:'Ecommerce Development',
        second:'Node JS Development',
        third:'   React JS Development'},
        {title: 'Premium' ,
        name: 'Web Development',
         price: 3000,
          para: 'Our expert in-house team uses cutting edge technologies to build softwares and custom web applications that are stunning, robust and scalable.',
         first:'UI & UX Design',
        second:'Fully Integrated Backend',
        third:'Online Payment option'},
    ],
    [
        {title: 'Basic' ,
        name: 'SEO',
         price: 1000,
          para: 'Learn everything you need to know about SEO in our SEO training course: Keyword research, OnPage, Technical SEO and more',
         first:"Learn How to rank your website in Google's top 10 in any niche",
        second:'Get a complete understanding of how search engines work',
        third:'Keyword research - Learn what your potential customers are searching for'},
        {title: 'Standard' ,
        name: 'SEO',
         price: 2000,
          para: 'Learn everything you need to know about SEO in our SEO training course: Keyword research, OnPage, Technical SEO and more',
         first:' Competitor Analysis - Know how your competitors are ranking',
        second:'Technical SEO - Learn what the search engines look for in your site',
        third:'Core web vitals - Learn what your website needs to be healthy'},
        {title: 'Premium' ,
        name: 'SEO',
         price: 3000,
          para: 'Learn everything you need to know about SEO in our SEO training course: Keyword research, OnPage, Technical SEO and more',
         first:'PageSpeed SEO - Learn how to make your pages load quickly',
        second:'Submit your sitemap to Google and make it easier for search engines to crawl and index your site',
        third:'Become an SEO expert and learn how to create backlinks and drive traffic to your website'},
    ],
    [
        {title: 'Basic' ,
        name: 'Digital Marketing',
         price: 1000,
          para: 'Learn Digital Marketing Strategies, SEO, B2B, B2C, Search, Keywords, Social Media, Email Marketing, Content vs Paid Ads',
         first:'Inbound Marketing',
        second:'Social Media Marketing',
        third:'Learn what is content marketing'},
        {title: 'Standard' ,
        name: 'Digital Marketing',
         price: 2000,
          para: 'Learn Digital Marketing Strategies, SEO, B2B, B2C, Search, Keywords, Social Media, Email Marketing, Content vs Paid Ads',
         first:'Learn examples of backlinks on digital regenesys and other',
        second:'Understand the concept of marketing ads and other strategies        ',
        third:'Important steps on keyword research - List of relevant keywords'},
        {title: 'Premium' ,
        name: 'Digital Marketing',
         price: 3000,
          para: 'Learn Digital Marketing Strategies, SEO, B2B, B2C, Search, Keywords, Social Media, Email Marketing, Content vs Paid Ads',
         first:'Know the different Social media platforms that you could use in doing business',
        second:'Know the different types of content',
        third:'Understand Email Marketing and how to use it to your advantage'},
    ]
]